// Code generated by MockGen. DO NOT EDIT.
// Source: auth/auth.go

// Package mock_auth 为自动生成的 GoMock 测试 Mock 包。
package mock_auth

import (
	json "encoding/json"
	reflect "reflect"
	time "time"

	auth "chat/server/auth"
	types "chat/server/store/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthHandler 是 AuthHandler 接口的 Mock 实现。
type MockAuthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthHandlerMockRecorder
}

// MockAuthHandlerMockRecorder 是 MockAuthHandler 的 Mock 记录器。
type MockAuthHandlerMockRecorder struct {
	mock *MockAuthHandler
}

// NewMockAuthHandler 创建新的 MockAuthHandler 实例。
func NewMockAuthHandler(ctrl *gomock.Controller) *MockAuthHandler {
	mock := &MockAuthHandler{ctrl: ctrl}
	mock.recorder = &MockAuthHandlerMockRecorder{mock}
	return mock
}

// EXPECT 返回一个记录期望调用的 Mock 记录器对象。
func (m *MockAuthHandler) EXPECT() *MockAuthHandlerMockRecorder {
	return m.recorder
}

// AddRecord Mock 实现 AuthHandler.AddRecord 方法。
func (m *MockAuthHandler) AddRecord(rec *auth.Rec, secret []byte, remoteAddr string) (*auth.Rec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecord", rec, secret, remoteAddr)
	ret0, _ := ret[0].(*auth.Rec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRecord 记录 AddRecord 的期望调用。
func (mr *MockAuthHandlerMockRecorder) AddRecord(rec, secret, remoteAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecord", reflect.TypeOf((*MockAuthHandler)(nil).AddRecord), rec, secret, remoteAddr)
}

// AsTag Mock 实现 AuthHandler.AsTag 方法。
func (m *MockAuthHandler) AsTag(token string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsTag", token)
	ret0, _ := ret[0].(string)
	return ret0
}

// AsTag 记录 AsTag 的期望调用。
func (mr *MockAuthHandlerMockRecorder) AsTag(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsTag", reflect.TypeOf((*MockAuthHandler)(nil).AsTag), token)
}

// Authenticate Mock 实现 AuthHandler.Authenticate 方法。
func (m *MockAuthHandler) Authenticate(secret []byte, remoteAddr string) (*auth.Rec, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", secret, remoteAddr)
	ret0, _ := ret[0].(*auth.Rec)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Authenticate 记录 Authenticate 的期望调用。
func (mr *MockAuthHandlerMockRecorder) Authenticate(secret, remoteAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthHandler)(nil).Authenticate), secret, remoteAddr)
}

// DelRecords Mock 实现 AuthHandler.DelRecords 方法。
func (m *MockAuthHandler) DelRecords(uid types.Uid) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelRecords", uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelRecords 记录 DelRecords 的期望调用。
func (mr *MockAuthHandlerMockRecorder) DelRecords(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelRecords", reflect.TypeOf((*MockAuthHandler)(nil).DelRecords), uid)
}

// GenSecret Mock 实现 AuthHandler.GenSecret 方法。
func (m *MockAuthHandler) GenSecret(rec *auth.Rec) ([]byte, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenSecret", rec)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenSecret 记录 GenSecret 的期望调用。
func (mr *MockAuthHandlerMockRecorder) GenSecret(rec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenSecret", reflect.TypeOf((*MockAuthHandler)(nil).GenSecret), rec)
}

// GetRealName Mock 实现 AuthHandler.GetRealName 方法。
func (m *MockAuthHandler) GetRealName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRealName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRealName 记录 GetRealName 的期望调用。
func (mr *MockAuthHandlerMockRecorder) GetRealName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRealName", reflect.TypeOf((*MockAuthHandler)(nil).GetRealName))
}

// GetResetParams Mock 实现 AuthHandler.GetResetParams 方法。
func (m *MockAuthHandler) GetResetParams(uid types.Uid) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResetParams", uid)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResetParams 记录 GetResetParams 的期望调用。
func (mr *MockAuthHandlerMockRecorder) GetResetParams(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResetParams", reflect.TypeOf((*MockAuthHandler)(nil).GetResetParams), uid)
}

// Init Mock 实现 AuthHandler.Init 方法。
func (m *MockAuthHandler) Init(jsonconf json.RawMessage, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", jsonconf, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init 记录 Init 的期望调用。
func (mr *MockAuthHandlerMockRecorder) Init(jsonconf, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockAuthHandler)(nil).Init), jsonconf, name)
}

// IsInitialized Mock 实现 AuthHandler.IsInitialized 方法。
func (m *MockAuthHandler) IsInitialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInitialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInitialized 记录 IsInitialized 的期望调用。
func (mr *MockAuthHandlerMockRecorder) IsInitialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInitialized", reflect.TypeOf((*MockAuthHandler)(nil).IsInitialized))
}

// IsUnique Mock 实现 AuthHandler.IsUnique 方法。
func (m *MockAuthHandler) IsUnique(secret []byte, remoteAddr string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUnique", secret, remoteAddr)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUnique 记录 IsUnique 的期望调用。
func (mr *MockAuthHandlerMockRecorder) IsUnique(secret, remoteAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUnique", reflect.TypeOf((*MockAuthHandler)(nil).IsUnique), secret, remoteAddr)
}

// RestrictedTags Mock 实现 AuthHandler.RestrictedTags 方法。
func (m *MockAuthHandler) RestrictedTags() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestrictedTags")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestrictedTags 记录 RestrictedTags 的期望调用。
func (mr *MockAuthHandlerMockRecorder) RestrictedTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestrictedTags", reflect.TypeOf((*MockAuthHandler)(nil).RestrictedTags))
}

// UpdateRecord Mock 实现 AuthHandler.UpdateRecord 方法。
func (m *MockAuthHandler) UpdateRecord(rec *auth.Rec, secret []byte, remoteAddr string) (*auth.Rec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecord", rec, secret, remoteAddr)
	ret0, _ := ret[0].(*auth.Rec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecord 记录 UpdateRecord 的期望调用。
func (mr *MockAuthHandlerMockRecorder) UpdateRecord(rec, secret, remoteAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecord", reflect.TypeOf((*MockAuthHandler)(nil).UpdateRecord), rec, secret, remoteAddr)
}
