// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: cluster.proto

package pbx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClusterFrameKind 标识集群帧中封装的内部操作。
type ClusterFrameKind int32

const (
	// CLUSTER_FRAME_UNSPECIFIED 禁止用于有效请求。
	ClusterFrameKind_CLUSTER_FRAME_UNSPECIFIED ClusterFrameKind = 0
	// CLUSTER_FRAME_PING 交换节点实例指纹。
	ClusterFrameKind_CLUSTER_FRAME_PING ClusterFrameKind = 1
	// CLUSTER_FRAME_TOPIC_MASTER 把 Topic Proxy 请求交给 Owner。
	ClusterFrameKind_CLUSTER_FRAME_TOPIC_MASTER ClusterFrameKind = 2
	// CLUSTER_FRAME_TOPIC_PROXY 把 Owner 响应交回 Topic Proxy。
	ClusterFrameKind_CLUSTER_FRAME_TOPIC_PROXY ClusterFrameKind = 3
	// CLUSTER_FRAME_ROUTE 路由节点级服务端消息。
	ClusterFrameKind_CLUSTER_FRAME_ROUTE ClusterFrameKind = 4
	// CLUSTER_FRAME_USER_CACHE 路由用户缓存和推送更新。
	ClusterFrameKind_CLUSTER_FRAME_USER_CACHE ClusterFrameKind = 5
)

// Enum value maps for ClusterFrameKind.
var (
	ClusterFrameKind_name = map[int32]string{
		0: "CLUSTER_FRAME_UNSPECIFIED",
		1: "CLUSTER_FRAME_PING",
		2: "CLUSTER_FRAME_TOPIC_MASTER",
		3: "CLUSTER_FRAME_TOPIC_PROXY",
		4: "CLUSTER_FRAME_ROUTE",
		5: "CLUSTER_FRAME_USER_CACHE",
	}
	ClusterFrameKind_value = map[string]int32{
		"CLUSTER_FRAME_UNSPECIFIED":  0,
		"CLUSTER_FRAME_PING":         1,
		"CLUSTER_FRAME_TOPIC_MASTER": 2,
		"CLUSTER_FRAME_TOPIC_PROXY":  3,
		"CLUSTER_FRAME_ROUTE":        4,
		"CLUSTER_FRAME_USER_CACHE":   5,
	}
)

func (x ClusterFrameKind) Enum() *ClusterFrameKind {
	p := new(ClusterFrameKind)
	*p = x
	return p
}

func (x ClusterFrameKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterFrameKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_proto_enumTypes[0].Descriptor()
}

func (ClusterFrameKind) Type() protoreflect.EnumType {
	return &file_cluster_proto_enumTypes[0]
}

func (x ClusterFrameKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterFrameKind.Descriptor instead.
func (ClusterFrameKind) EnumDescriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

// ClusterFrame 是节点间 gRPC Lane 的版本化传输信封。
type ClusterFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_id 隔离不同环境或租户的逻辑集群。
	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// source_node 是发送节点的静态成员名称。
	SourceNode string `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	// source_instance 是进程每次启动生成的新实例指纹。
	SourceInstance int64 `protobuf:"varint,3,opt,name=source_instance,json=sourceInstance,proto3" json:"source_instance,omitempty"`
	// protocol_version 是节点间数据面协议版本。
	ProtocolVersion int32 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// lane 是当前帧所属的有序 Lane 编号。
	Lane uint32 `protobuf:"varint,5,opt,name=lane,proto3" json:"lane,omitempty"`
	// sequence 是单条流内从 1 开始严格递增的序号。
	Sequence uint64 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// request_id 在重试和响应关联期间保持稳定。
	RequestId string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// kind 标识内部调用类型。
	Kind ClusterFrameKind `protobuf:"varint,8,opt,name=kind,proto3,enum=pbx.ClusterFrameKind" json:"kind,omitempty"`
	// payload 保存当前版本的内部请求或响应编码。
	Payload []byte `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	// response 为 true 时该帧是 request_id 对应的响应。
	Response bool `protobuf:"varint,10,opt,name=response,proto3" json:"response,omitempty"`
	// error 非空表示远端没有成功处理请求。
	Error string `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	// cluster_epoch 是发送节点已经提交的成员视图任期。
	ClusterEpoch int64 `protobuf:"varint,12,opt,name=cluster_epoch,json=clusterEpoch,proto3" json:"cluster_epoch,omitempty"`
	// ring_signature 用于拒绝尚未收敛的 Topic 路由。
	RingSignature string `protobuf:"bytes,13,opt,name=ring_signature,json=ringSignature,proto3" json:"ring_signature,omitempty"`
	// min_protocol_version 是发送节点仍能兼容的最早数据面协议版本。
	MinProtocolVersion int32 `protobuf:"varint,14,opt,name=min_protocol_version,json=minProtocolVersion,proto3" json:"min_protocol_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClusterFrame) Reset() {
	*x = ClusterFrame{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterFrame) ProtoMessage() {}

func (x *ClusterFrame) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterFrame.ProtoReflect.Descriptor instead.
func (*ClusterFrame) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterFrame) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterFrame) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *ClusterFrame) GetSourceInstance() int64 {
	if x != nil {
		return x.SourceInstance
	}
	return 0
}

func (x *ClusterFrame) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ClusterFrame) GetLane() uint32 {
	if x != nil {
		return x.Lane
	}
	return 0
}

func (x *ClusterFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ClusterFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClusterFrame) GetKind() ClusterFrameKind {
	if x != nil {
		return x.Kind
	}
	return ClusterFrameKind_CLUSTER_FRAME_UNSPECIFIED
}

func (x *ClusterFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClusterFrame) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

func (x *ClusterFrame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ClusterFrame) GetClusterEpoch() int64 {
	if x != nil {
		return x.ClusterEpoch
	}
	return 0
}

func (x *ClusterFrame) GetRingSignature() string {
	if x != nil {
		return x.RingSignature
	}
	return ""
}

func (x *ClusterFrame) GetMinProtocolVersion() int32 {
	if x != nil {
		return x.MinProtocolVersion
	}
	return 0
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\x03pbx\"\xe6\x03\n" +
	"\fClusterFrame\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\x12'\n" +
	"\x0fsource_instance\x18\x03 \x01(\x03R\x0esourceInstance\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\x05R\x0fprotocolVersion\x12\x12\n" +
	"\x04lane\x18\x05 \x01(\rR\x04lane\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12)\n" +
	"\x04kind\x18\b \x01(\x0e2\x15.pbx.ClusterFrameKindR\x04kind\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12\x1a\n" +
	"\bresponse\x18\n" +
	" \x01(\bR\bresponse\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12#\n" +
	"\rcluster_epoch\x18\f \x01(\x03R\fclusterEpoch\x12%\n" +
	"\x0ering_signature\x18\r \x01(\tR\rringSignature\x120\n" +
	"\x14min_protocol_version\x18\x0e \x01(\x05R\x12minProtocolVersion*\xbf\x01\n" +
	"\x10ClusterFrameKind\x12\x1d\n" +
	"\x19CLUSTER_FRAME_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CLUSTER_FRAME_PING\x10\x01\x12\x1e\n" +
	"\x1aCLUSTER_FRAME_TOPIC_MASTER\x10\x02\x12\x1d\n" +
	"\x19CLUSTER_FRAME_TOPIC_PROXY\x10\x03\x12\x17\n" +
	"\x13CLUSTER_FRAME_ROUTE\x10\x04\x12\x1c\n" +
	"\x18CLUSTER_FRAME_USER_CACHE\x10\x052F\n" +
	"\x10ClusterTransport\x122\n" +
	"\x04Lane\x12\x11.pbx.ClusterFrame\x1a\x11.pbx.ClusterFrame\"\x00(\x010\x01B\x0eZ\fchat/api/pbxb\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cluster_proto_goTypes = []any{
	(ClusterFrameKind)(0), // 0: pbx.ClusterFrameKind
	(*ClusterFrame)(nil),  // 1: pbx.ClusterFrame
}
var file_cluster_proto_depIdxs = []int32{
	0, // 0: pbx.ClusterFrame.kind:type_name -> pbx.ClusterFrameKind
	1, // 1: pbx.ClusterTransport.Lane:input_type -> pbx.ClusterFrame
	1, // 2: pbx.ClusterTransport.Lane:output_type -> pbx.ClusterFrame
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		EnumInfos:         file_cluster_proto_enumTypes,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
