// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: cluster.proto

package pbx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterTransport_Lane_FullMethodName = "/pbx.ClusterTransport/Lane"
)

// ClusterTransportClient is the client API for ClusterTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterTransport 是 IM 节点之间专用的有序数据面服务。
// 每个逻辑 Lane 使用一条长期双向流；同一 Topic 始终映射到同一 Lane。
type ClusterTransportClient interface {
	// Lane 在节点间传输请求与响应帧，并依靠 HTTP/2 流保证帧内顺序。
	Lane(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClusterFrame, ClusterFrame], error)
}

type clusterTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterTransportClient(cc grpc.ClientConnInterface) ClusterTransportClient {
	return &clusterTransportClient{cc}
}

func (c *clusterTransportClient) Lane(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClusterFrame, ClusterFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterTransport_ServiceDesc.Streams[0], ClusterTransport_Lane_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClusterFrame, ClusterFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterTransport_LaneClient = grpc.BidiStreamingClient[ClusterFrame, ClusterFrame]

// ClusterTransportServer is the server API for ClusterTransport service.
// All implementations must embed UnimplementedClusterTransportServer
// for forward compatibility.
//
// ClusterTransport 是 IM 节点之间专用的有序数据面服务。
// 每个逻辑 Lane 使用一条长期双向流；同一 Topic 始终映射到同一 Lane。
type ClusterTransportServer interface {
	// Lane 在节点间传输请求与响应帧，并依靠 HTTP/2 流保证帧内顺序。
	Lane(grpc.BidiStreamingServer[ClusterFrame, ClusterFrame]) error
	mustEmbedUnimplementedClusterTransportServer()
}

// UnimplementedClusterTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterTransportServer struct{}

func (UnimplementedClusterTransportServer) Lane(grpc.BidiStreamingServer[ClusterFrame, ClusterFrame]) error {
	return status.Error(codes.Unimplemented, "method Lane not implemented")
}
func (UnimplementedClusterTransportServer) mustEmbedUnimplementedClusterTransportServer() {}
func (UnimplementedClusterTransportServer) testEmbeddedByValue()                          {}

// UnsafeClusterTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterTransportServer will
// result in compilation errors.
type UnsafeClusterTransportServer interface {
	mustEmbedUnimplementedClusterTransportServer()
}

func RegisterClusterTransportServer(s grpc.ServiceRegistrar, srv ClusterTransportServer) {
	// If the following call panics, it indicates UnimplementedClusterTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterTransport_ServiceDesc, srv)
}

func _ClusterTransport_Lane_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterTransportServer).Lane(&grpc.GenericServerStream[ClusterFrame, ClusterFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterTransport_LaneServer = grpc.BidiStreamingServer[ClusterFrame, ClusterFrame]

// ClusterTransport_ServiceDesc is the grpc.ServiceDesc for ClusterTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbx.ClusterTransport",
	HandlerType: (*ClusterTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Lane",
			Handler:       _ClusterTransport_Lane_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cluster.proto",
}
