// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: file.proto

package pbx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheme 保存该消息字段对应的协议值。
	Scheme string `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// secret 保存该消息字段对应的协议值。
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *Auth) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Auth) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// 文件元数据描述
type FileMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 保存该消息字段对应的协议值。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// mime_type 保存该消息字段对应的协议值。
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// etag 保存该消息字段对应的协议值。
	Etag string `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	// size 保存该消息字段对应的协议值。
	Size          int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMeta) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileMeta) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *FileMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 文件上传请求
type FileUpReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 请求认证凭据
	Auth *Auth `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	// 该上传文件所属的目标主题（Topic）
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// 上传的文件元数据
	Meta *FileMeta `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	// 文件数据块
	Content       []byte `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUpReq) Reset() {
	*x = FileUpReq{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpReq) ProtoMessage() {}

func (x *FileUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpReq.ProtoReflect.Descriptor instead.
func (*FileUpReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *FileUpReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileUpReq) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *FileUpReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FileUpReq) GetMeta() *FileMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *FileUpReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// 文件上传响应
type FileUpResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 响应状态码
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// 响应文本消息
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// meta 保存该消息字段对应的协议值。
	Meta *FileMeta `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	// 新上传重定向 URL 位置
	RedirUrl      string `protobuf:"bytes,5,opt,name=redir_url,json=redirUrl,proto3" json:"redir_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUpResp) Reset() {
	*x = FileUpResp{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpResp) ProtoMessage() {}

func (x *FileUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpResp.ProtoReflect.Descriptor instead.
func (*FileUpResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *FileUpResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileUpResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FileUpResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FileUpResp) GetMeta() *FileMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *FileUpResp) GetRedirUrl() string {
	if x != nil {
		return x.RedirUrl
	}
	return ""
}

// 文件下载请求
type FileDownReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 请求认证凭据
	Auth *Auth `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	// 待下载的目标文件 URI
	Uri string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	// ETag 缓存校验
	IfModified    string `protobuf:"bytes,4,opt,name=if_modified,json=ifModified,proto3" json:"if_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownReq) Reset() {
	*x = FileDownReq{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownReq) ProtoMessage() {}

func (x *FileDownReq) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownReq.ProtoReflect.Descriptor instead.
func (*FileDownReq) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

func (x *FileDownReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileDownReq) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *FileDownReq) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *FileDownReq) GetIfModified() string {
	if x != nil {
		return x.IfModified
	}
	return ""
}

// 文件下载响应
type FileDownResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 响应状态码
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// 响应文本消息
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// meta 保存该消息字段对应的协议值。
	Meta *FileMeta `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	// 重定向文件位置
	RedirUrl string `protobuf:"bytes,5,opt,name=redir_url,json=redirUrl,proto3" json:"redir_url,omitempty"`
	// 文件数据块字节流
	Content       []byte `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownResp) Reset() {
	*x = FileDownResp{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownResp) ProtoMessage() {}

func (x *FileDownResp) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownResp.ProtoReflect.Descriptor instead.
func (*FileDownResp) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *FileDownResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileDownResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FileDownResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FileDownResp) GetMeta() *FileMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *FileDownResp) GetRedirUrl() string {
	if x != nil {
		return x.RedirUrl
	}
	return ""
}

func (x *FileDownResp) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\x03pbx\"6\n" +
	"\x04Auth\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"c\n" +
	"\bFileMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\x8d\x01\n" +
	"\tFileUpReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\x04auth\x18\x02 \x01(\v2\t.pbx.AuthR\x04auth\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12!\n" +
	"\x04meta\x18\x04 \x01(\v2\r.pbx.FileMetaR\x04meta\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\"\x84\x01\n" +
	"\n" +
	"FileUpResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12!\n" +
	"\x04meta\x18\x04 \x01(\v2\r.pbx.FileMetaR\x04meta\x12\x1b\n" +
	"\tredir_url\x18\x05 \x01(\tR\bredirUrl\"o\n" +
	"\vFileDownReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\x04auth\x18\x02 \x01(\v2\t.pbx.AuthR\x04auth\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x1f\n" +
	"\vif_modified\x18\x04 \x01(\tR\n" +
	"ifModified\"\xa0\x01\n" +
	"\fFileDownResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12!\n" +
	"\x04meta\x18\x04 \x01(\v2\r.pbx.FileMetaR\x04meta\x12\x1b\n" +
	"\tredir_url\x18\x05 \x01(\tR\bredirUrl\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontentB\x0eZ\fchat/api/pbxb\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_file_proto_goTypes = []any{
	(*Auth)(nil),         // 0: pbx.Auth
	(*FileMeta)(nil),     // 1: pbx.FileMeta
	(*FileUpReq)(nil),    // 2: pbx.FileUpReq
	(*FileUpResp)(nil),   // 3: pbx.FileUpResp
	(*FileDownReq)(nil),  // 4: pbx.FileDownReq
	(*FileDownResp)(nil), // 5: pbx.FileDownResp
}
var file_file_proto_depIdxs = []int32{
	0, // 0: pbx.FileUpReq.auth:type_name -> pbx.Auth
	1, // 1: pbx.FileUpReq.meta:type_name -> pbx.FileMeta
	1, // 2: pbx.FileUpResp.meta:type_name -> pbx.FileMeta
	0, // 3: pbx.FileDownReq.auth:type_name -> pbx.Auth
	1, // 4: pbx.FileDownResp.meta:type_name -> pbx.FileMeta
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
