// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: node.proto

package pbx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x03pbx\x1a\n" +
	"chat.proto\x1a\n" +
	"file.proto2\xaf\x01\n" +
	"\x04Node\x123\n" +
	"\vMessageLoop\x12\x0e.pbx.ClientMsg\x1a\x0e.pbx.ServerMsg\"\x00(\x010\x01\x127\n" +
	"\x10LargeFileReceive\x12\x0e.pbx.FileUpReq\x1a\x0f.pbx.FileUpResp\"\x00(\x01\x129\n" +
	"\x0eLargeFileServe\x12\x10.pbx.FileDownReq\x1a\x11.pbx.FileDownResp\"\x000\x01B\x0eZ\fchat/api/pbxb\x06proto3"

var file_node_proto_goTypes = []any{
	(*ClientMsg)(nil),    // 0: pbx.ClientMsg
	(*FileUpReq)(nil),    // 1: pbx.FileUpReq
	(*FileDownReq)(nil),  // 2: pbx.FileDownReq
	(*ServerMsg)(nil),    // 3: pbx.ServerMsg
	(*FileUpResp)(nil),   // 4: pbx.FileUpResp
	(*FileDownResp)(nil), // 5: pbx.FileDownResp
}
var file_node_proto_depIdxs = []int32{
	0, // 0: pbx.Node.MessageLoop:input_type -> pbx.ClientMsg
	1, // 1: pbx.Node.LargeFileReceive:input_type -> pbx.FileUpReq
	2, // 2: pbx.Node.LargeFileServe:input_type -> pbx.FileDownReq
	3, // 3: pbx.Node.MessageLoop:output_type -> pbx.ServerMsg
	4, // 4: pbx.Node.LargeFileReceive:output_type -> pbx.FileUpResp
	5, // 5: pbx.Node.LargeFileServe:output_type -> pbx.FileDownResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_chat_proto_init()
	file_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
