// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: node.proto

package pbx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_MessageLoop_FullMethodName      = "/pbx.Node/MessageLoop"
	Node_LargeFileReceive_FullMethodName = "/pbx.Node/LargeFileReceive"
	Node_LargeFileServe_FullMethodName   = "/pbx.Node/LargeFileServe"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC 客户端需要实现的主节点服务
type NodeClient interface {
	// 客户端发送 ClientMsg 流，服务端响应 ServerMsg 流
	MessageLoop(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMsg, ServerMsg], error)
	// 大文件上传接口：包含数据块流的请求
	LargeFileReceive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileUpReq, FileUpResp], error)
	// 大文件下载接口：包含数据块流的响应
	LargeFileServe(ctx context.Context, in *FileDownReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileDownResp], error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) MessageLoop(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMsg, ServerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Node_ServiceDesc.Streams[0], Node_MessageLoop_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMsg, ServerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_MessageLoopClient = grpc.BidiStreamingClient[ClientMsg, ServerMsg]

func (c *nodeClient) LargeFileReceive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileUpReq, FileUpResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Node_ServiceDesc.Streams[1], Node_LargeFileReceive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileUpReq, FileUpResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_LargeFileReceiveClient = grpc.ClientStreamingClient[FileUpReq, FileUpResp]

func (c *nodeClient) LargeFileServe(ctx context.Context, in *FileDownReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileDownResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Node_ServiceDesc.Streams[2], Node_LargeFileServe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileDownReq, FileDownResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_LargeFileServeClient = grpc.ServerStreamingClient[FileDownResp]

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
//
// gRPC 客户端需要实现的主节点服务
type NodeServer interface {
	// 客户端发送 ClientMsg 流，服务端响应 ServerMsg 流
	MessageLoop(grpc.BidiStreamingServer[ClientMsg, ServerMsg]) error
	// 大文件上传接口：包含数据块流的请求
	LargeFileReceive(grpc.ClientStreamingServer[FileUpReq, FileUpResp]) error
	// 大文件下载接口：包含数据块流的响应
	LargeFileServe(*FileDownReq, grpc.ServerStreamingServer[FileDownResp]) error
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) MessageLoop(grpc.BidiStreamingServer[ClientMsg, ServerMsg]) error {
	return status.Error(codes.Unimplemented, "method MessageLoop not implemented")
}
func (UnimplementedNodeServer) LargeFileReceive(grpc.ClientStreamingServer[FileUpReq, FileUpResp]) error {
	return status.Error(codes.Unimplemented, "method LargeFileReceive not implemented")
}
func (UnimplementedNodeServer) LargeFileServe(*FileDownReq, grpc.ServerStreamingServer[FileDownResp]) error {
	return status.Error(codes.Unimplemented, "method LargeFileServe not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call panics, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_MessageLoop_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServer).MessageLoop(&grpc.GenericServerStream[ClientMsg, ServerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_MessageLoopServer = grpc.BidiStreamingServer[ClientMsg, ServerMsg]

func _Node_LargeFileReceive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServer).LargeFileReceive(&grpc.GenericServerStream[FileUpReq, FileUpResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_LargeFileReceiveServer = grpc.ClientStreamingServer[FileUpReq, FileUpResp]

func _Node_LargeFileServe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDownReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServer).LargeFileServe(m, &grpc.GenericServerStream[FileDownReq, FileDownResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Node_LargeFileServeServer = grpc.ServerStreamingServer[FileDownResp]

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbx.Node",
	HandlerType: (*NodeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageLoop",
			Handler:       _Node_MessageLoop_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "LargeFileReceive",
			Handler:       _Node_LargeFileReceive_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LargeFileServe",
			Handler:       _Node_LargeFileServe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node.proto",
}
