// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: plugin.proto

package pbx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 插件响应代码
type RespCode int32

const (
	// 指示 IM 服务端按默认流程继续处理客户端请求
	RespCode_CONTINUE RespCode = 0
	// 静默丢弃该请求，如同客户端未曾发送
	RespCode_DROP RespCode = 1
	// 直接向客户端发送指定的 srvmsg 响应。ServerResp 必须包含非空的 srvmsg
	RespCode_RESPOND RespCode = 2
	// 将客户端的原始请求替换为提供的 clmsg 请求，然后再继续处理。ServerResp 必须包含非空的 clmsg
	RespCode_REPLACE RespCode = 3
)

// Enum value maps for RespCode.
var (
	RespCode_name = map[int32]string{
		0: "CONTINUE",
		1: "DROP",
		2: "RESPOND",
		3: "REPLACE",
	}
	RespCode_value = map[string]int32{
		"CONTINUE": 0,
		"DROP":     1,
		"RESPOND":  2,
		"REPLACE":  3,
	}
)

func (x RespCode) Enum() *RespCode {
	p := new(RespCode)
	*p = x
	return p
}

func (x RespCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespCode) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (RespCode) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x RespCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespCode.Descriptor instead.
func (RespCode) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type Crud int32

const (
	// CREATE 表示该枚举对应的协议状态。
	Crud_CREATE Crud = 0
	// UPDATE 表示该枚举对应的协议状态。
	Crud_UPDATE Crud = 1
	// DELETE 表示该枚举对应的协议状态。
	Crud_DELETE Crud = 2
)

// Enum value maps for Crud.
var (
	Crud_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	Crud_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x Crud) Enum() *Crud {
	p := new(Crud)
	*p = x
	return p
}

func (x Crud) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Crud) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (Crud) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x Crud) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Crud.Descriptor instead.
func (Crud) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

// 占位空消息
type Unused struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unused) Reset() {
	*x = Unused{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unused) ProtoMessage() {}

func (x *Unused) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unused.ProtoReflect.Descriptor instead.
func (*Unused) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// ServerResp 定义 ServerResp 的 Protobuf 消息结构。
type ServerResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status 保存该消息字段对应的协议值。
	Status RespCode `protobuf:"varint,1,opt,name=status,proto3,enum=pbx.RespCode" json:"status,omitempty"`
	// srvmsg 保存该消息字段对应的协议值。
	Srvmsg *ServerMsg `protobuf:"bytes,2,opt,name=srvmsg,proto3" json:"srvmsg,omitempty"`
	// clmsg 保存该消息字段对应的协议值。
	Clmsg         *ClientMsg `protobuf:"bytes,3,opt,name=clmsg,proto3" json:"clmsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResp) Reset() {
	*x = ServerResp{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResp) ProtoMessage() {}

func (x *ServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResp.ProtoReflect.Descriptor instead.
func (*ServerResp) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ServerResp) GetStatus() RespCode {
	if x != nil {
		return x.Status
	}
	return RespCode_CONTINUE
}

func (x *ServerResp) GetSrvmsg() *ServerMsg {
	if x != nil {
		return x.Srvmsg
	}
	return nil
}

func (x *ServerResp) GetClmsg() *ClientMsg {
	if x != nil {
		return x.Clmsg
	}
	return nil
}

// 会话上下文消息
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id 保存该消息字段对应的协议值。
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// user_id 保存该消息字段对应的协议值。
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// auth_level 保存该消息字段对应的协议值。
	AuthLevel AuthLevel `protobuf:"varint,3,opt,name=auth_level,json=authLevel,proto3,enum=pbx.AuthLevel" json:"auth_level,omitempty"`
	// remote_addr 保存该消息字段对应的协议值。
	RemoteAddr string `protobuf:"bytes,4,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	// user_agent 保存该消息字段对应的协议值。
	UserAgent string `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// device_id 保存该消息字段对应的协议值。
	DeviceId string `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// language 保存该消息字段对应的协议值。
	Language      string `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetAuthLevel() AuthLevel {
	if x != nil {
		return x.AuthLevel
	}
	return AuthLevel_NONE
}

func (x *Session) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Session) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// ClientReq 定义 ClientReq 的 Protobuf 消息结构。
type ClientReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// msg 保存该消息字段对应的协议值。
	Msg *ClientMsg `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// sess 保存该消息字段对应的协议值。
	Sess          *Session `protobuf:"bytes,2,opt,name=sess,proto3" json:"sess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReq) Reset() {
	*x = ClientReq{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReq) ProtoMessage() {}

func (x *ClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReq.ProtoReflect.Descriptor instead.
func (*ClientReq) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ClientReq) GetMsg() *ClientMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientReq) GetSess() *Session {
	if x != nil {
		return x.Sess
	}
	return nil
}

type SearchQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 保存该消息字段对应的协议值。
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// query 保存该消息字段对应的协议值。
	Query         string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuery) Reset() {
	*x = SearchQuery{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuery) ProtoMessage() {}

func (x *SearchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuery.ProtoReflect.Descriptor instead.
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *SearchQuery) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// SearchFound 定义 SearchFound 的 Protobuf 消息结构。
type SearchFound struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status 保存该消息字段对应的协议值。
	Status RespCode `protobuf:"varint,1,opt,name=status,proto3,enum=pbx.RespCode" json:"status,omitempty"`
	// 若 status == REPLACE，则表示替换后的新搜索查询语句，否则未设置
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// 搜索结果列表
	Result        []*TopicSub `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFound) Reset() {
	*x = SearchFound{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFound) ProtoMessage() {}

func (x *SearchFound) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFound.ProtoReflect.Descriptor instead.
func (*SearchFound) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *SearchFound) GetStatus() RespCode {
	if x != nil {
		return x.Status
	}
	return RespCode_CONTINUE
}

func (x *SearchFound) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchFound) GetResult() []*TopicSub {
	if x != nil {
		return x.Result
	}
	return nil
}

// TopicEvent 定义 TopicEvent 的 Protobuf 消息结构。
type TopicEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action 保存该消息字段对应的协议值。
	Action Crud `protobuf:"varint,1,opt,name=action,proto3,enum=pbx.Crud" json:"action,omitempty"`
	// name 保存该消息字段对应的协议值。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// desc 保存该消息字段对应的协议值。
	Desc          *TopicDesc `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicEvent) Reset() {
	*x = TopicEvent{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicEvent) ProtoMessage() {}

func (x *TopicEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicEvent.ProtoReflect.Descriptor instead.
func (*TopicEvent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *TopicEvent) GetAction() Crud {
	if x != nil {
		return x.Action
	}
	return Crud_CREATE
}

func (x *TopicEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicEvent) GetDesc() *TopicDesc {
	if x != nil {
		return x.Desc
	}
	return nil
}

// AccountEvent 定义 AccountEvent 的 Protobuf 消息结构。
type AccountEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action 保存该消息字段对应的协议值。
	Action Crud `protobuf:"varint,1,opt,name=action,proto3,enum=pbx.Crud" json:"action,omitempty"`
	// user_id 保存该消息字段对应的协议值。
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// default_acs 保存该消息字段对应的协议值。
	DefaultAcs *DefaultAcsMode `protobuf:"bytes,3,opt,name=default_acs,json=defaultAcs,proto3" json:"default_acs,omitempty"`
	// public 保存该消息字段对应的协议值。
	Public []byte `protobuf:"bytes,4,opt,name=public,proto3" json:"public,omitempty"`
	// 用于用户发现的可索引标签
	Tags          []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountEvent) Reset() {
	*x = AccountEvent{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountEvent) ProtoMessage() {}

func (x *AccountEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountEvent.ProtoReflect.Descriptor instead.
func (*AccountEvent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *AccountEvent) GetAction() Crud {
	if x != nil {
		return x.Action
	}
	return Crud_CREATE
}

func (x *AccountEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountEvent) GetDefaultAcs() *DefaultAcsMode {
	if x != nil {
		return x.DefaultAcs
	}
	return nil
}

func (x *AccountEvent) GetPublic() []byte {
	if x != nil {
		return x.Public
	}
	return nil
}

func (x *AccountEvent) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// SubscriptionEvent 定义 SubscriptionEvent 的 Protobuf 消息结构。
type SubscriptionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action 保存该消息字段对应的协议值。
	Action Crud `protobuf:"varint,1,opt,name=action,proto3,enum=pbx.Crud" json:"action,omitempty"`
	// topic 保存该消息字段对应的协议值。
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// user_id 保存该消息字段对应的协议值。
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// del_id 保存该消息字段对应的协议值。
	DelId int32 `protobuf:"varint,4,opt,name=del_id,json=delId,proto3" json:"del_id,omitempty"`
	// read_id 保存该消息字段对应的协议值。
	ReadId int32 `protobuf:"varint,5,opt,name=read_id,json=readId,proto3" json:"read_id,omitempty"`
	// recv_id 保存该消息字段对应的协议值。
	RecvId int32 `protobuf:"varint,6,opt,name=recv_id,json=recvId,proto3" json:"recv_id,omitempty"`
	// mode 保存该消息字段对应的协议值。
	Mode *AccessMode `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
	// private 保存该消息字段对应的协议值。
	Private       []byte `protobuf:"bytes,8,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionEvent) Reset() {
	*x = SubscriptionEvent{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionEvent) ProtoMessage() {}

func (x *SubscriptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionEvent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *SubscriptionEvent) GetAction() Crud {
	if x != nil {
		return x.Action
	}
	return Crud_CREATE
}

func (x *SubscriptionEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscriptionEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscriptionEvent) GetDelId() int32 {
	if x != nil {
		return x.DelId
	}
	return 0
}

func (x *SubscriptionEvent) GetReadId() int32 {
	if x != nil {
		return x.ReadId
	}
	return 0
}

func (x *SubscriptionEvent) GetRecvId() int32 {
	if x != nil {
		return x.RecvId
	}
	return 0
}

func (x *SubscriptionEvent) GetMode() *AccessMode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *SubscriptionEvent) GetPrivate() []byte {
	if x != nil {
		return x.Private
	}
	return nil
}

// MessageEvent 定义 MessageEvent 的 Protobuf 消息结构。
type MessageEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action 保存该消息字段对应的协议值。
	Action Crud `protobuf:"varint,1,opt,name=action,proto3,enum=pbx.Crud" json:"action,omitempty"`
	// msg 保存该消息字段对应的协议值。
	Msg           *ServerData `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *MessageEvent) GetAction() Crud {
	if x != nil {
		return x.Action
	}
	return Crud_CREATE
}

func (x *MessageEvent) GetMsg() *ServerData {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x03pbx\x1a\n" +
	"chat.proto\"\b\n" +
	"\x06Unused\"\x81\x01\n" +
	"\n" +
	"ServerResp\x12%\n" +
	"\x06status\x18\x01 \x01(\x0e2\r.pbx.RespCodeR\x06status\x12&\n" +
	"\x06srvmsg\x18\x02 \x01(\v2\x0e.pbx.ServerMsgR\x06srvmsg\x12$\n" +
	"\x05clmsg\x18\x03 \x01(\v2\x0e.pbx.ClientMsgR\x05clmsg\"\xe9\x01\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\n" +
	"auth_level\x18\x03 \x01(\x0e2\x0e.pbx.AuthLevelR\tauthLevel\x12\x1f\n" +
	"\vremote_addr\x18\x04 \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\"O\n" +
	"\tClientReq\x12 \n" +
	"\x03msg\x18\x01 \x01(\v2\x0e.pbx.ClientMsgR\x03msg\x12 \n" +
	"\x04sess\x18\x02 \x01(\v2\f.pbx.SessionR\x04sess\"<\n" +
	"\vSearchQuery\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"q\n" +
	"\vSearchFound\x12%\n" +
	"\x06status\x18\x01 \x01(\x0e2\r.pbx.RespCodeR\x06status\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12%\n" +
	"\x06result\x18\x03 \x03(\v2\r.pbx.TopicSubR\x06result\"g\n" +
	"\n" +
	"TopicEvent\x12!\n" +
	"\x06action\x18\x01 \x01(\x0e2\t.pbx.CrudR\x06action\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\x04desc\x18\x03 \x01(\v2\x0e.pbx.TopicDescR\x04desc\"\xac\x01\n" +
	"\fAccountEvent\x12!\n" +
	"\x06action\x18\x01 \x01(\x0e2\t.pbx.CrudR\x06action\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x124\n" +
	"\vdefault_acs\x18\x03 \x01(\v2\x13.pbx.DefaultAcsModeR\n" +
	"defaultAcs\x12\x16\n" +
	"\x06public\x18\x04 \x01(\fR\x06public\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\"\xed\x01\n" +
	"\x11SubscriptionEvent\x12!\n" +
	"\x06action\x18\x01 \x01(\x0e2\t.pbx.CrudR\x06action\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x15\n" +
	"\x06del_id\x18\x04 \x01(\x05R\x05delId\x12\x17\n" +
	"\aread_id\x18\x05 \x01(\x05R\x06readId\x12\x17\n" +
	"\arecv_id\x18\x06 \x01(\x05R\x06recvId\x12#\n" +
	"\x04mode\x18\a \x01(\v2\x0f.pbx.AccessModeR\x04mode\x12\x18\n" +
	"\aprivate\x18\b \x01(\fR\aprivate\"T\n" +
	"\fMessageEvent\x12!\n" +
	"\x06action\x18\x01 \x01(\x0e2\t.pbx.CrudR\x06action\x12!\n" +
	"\x03msg\x18\x02 \x01(\v2\x0f.pbx.ServerDataR\x03msg*<\n" +
	"\bRespCode\x12\f\n" +
	"\bCONTINUE\x10\x00\x12\b\n" +
	"\x04DROP\x10\x01\x12\v\n" +
	"\aRESPOND\x10\x02\x12\v\n" +
	"\aREPLACE\x10\x03**\n" +
	"\x04Crud\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\x9f\x02\n" +
	"\x06Plugin\x12-\n" +
	"\bFireHose\x12\x0e.pbx.ClientReq\x1a\x0f.pbx.ServerResp\"\x00\x12,\n" +
	"\x04Find\x12\x10.pbx.SearchQuery\x1a\x10.pbx.SearchFound\"\x00\x12+\n" +
	"\aAccount\x12\x11.pbx.AccountEvent\x1a\v.pbx.Unused\"\x00\x12'\n" +
	"\x05Topic\x12\x0f.pbx.TopicEvent\x1a\v.pbx.Unused\"\x00\x125\n" +
	"\fSubscription\x12\x16.pbx.SubscriptionEvent\x1a\v.pbx.Unused\"\x00\x12+\n" +
	"\aMessage\x12\x11.pbx.MessageEvent\x1a\v.pbx.Unused\"\x00B\x0eZ\fchat/api/pbxb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plugin_proto_goTypes = []any{
	(RespCode)(0),             // 0: pbx.RespCode
	(Crud)(0),                 // 1: pbx.Crud
	(*Unused)(nil),            // 2: pbx.Unused
	(*ServerResp)(nil),        // 3: pbx.ServerResp
	(*Session)(nil),           // 4: pbx.Session
	(*ClientReq)(nil),         // 5: pbx.ClientReq
	(*SearchQuery)(nil),       // 6: pbx.SearchQuery
	(*SearchFound)(nil),       // 7: pbx.SearchFound
	(*TopicEvent)(nil),        // 8: pbx.TopicEvent
	(*AccountEvent)(nil),      // 9: pbx.AccountEvent
	(*SubscriptionEvent)(nil), // 10: pbx.SubscriptionEvent
	(*MessageEvent)(nil),      // 11: pbx.MessageEvent
	(*ServerMsg)(nil),         // 12: pbx.ServerMsg
	(*ClientMsg)(nil),         // 13: pbx.ClientMsg
	(AuthLevel)(0),            // 14: pbx.AuthLevel
	(*TopicSub)(nil),          // 15: pbx.TopicSub
	(*TopicDesc)(nil),         // 16: pbx.TopicDesc
	(*DefaultAcsMode)(nil),    // 17: pbx.DefaultAcsMode
	(*AccessMode)(nil),        // 18: pbx.AccessMode
	(*ServerData)(nil),        // 19: pbx.ServerData
}
var file_plugin_proto_depIdxs = []int32{
	0,  // 0: pbx.ServerResp.status:type_name -> pbx.RespCode
	12, // 1: pbx.ServerResp.srvmsg:type_name -> pbx.ServerMsg
	13, // 2: pbx.ServerResp.clmsg:type_name -> pbx.ClientMsg
	14, // 3: pbx.Session.auth_level:type_name -> pbx.AuthLevel
	13, // 4: pbx.ClientReq.msg:type_name -> pbx.ClientMsg
	4,  // 5: pbx.ClientReq.sess:type_name -> pbx.Session
	0,  // 6: pbx.SearchFound.status:type_name -> pbx.RespCode
	15, // 7: pbx.SearchFound.result:type_name -> pbx.TopicSub
	1,  // 8: pbx.TopicEvent.action:type_name -> pbx.Crud
	16, // 9: pbx.TopicEvent.desc:type_name -> pbx.TopicDesc
	1,  // 10: pbx.AccountEvent.action:type_name -> pbx.Crud
	17, // 11: pbx.AccountEvent.default_acs:type_name -> pbx.DefaultAcsMode
	1,  // 12: pbx.SubscriptionEvent.action:type_name -> pbx.Crud
	18, // 13: pbx.SubscriptionEvent.mode:type_name -> pbx.AccessMode
	1,  // 14: pbx.MessageEvent.action:type_name -> pbx.Crud
	19, // 15: pbx.MessageEvent.msg:type_name -> pbx.ServerData
	5,  // 16: pbx.Plugin.FireHose:input_type -> pbx.ClientReq
	6,  // 17: pbx.Plugin.Find:input_type -> pbx.SearchQuery
	9,  // 18: pbx.Plugin.Account:input_type -> pbx.AccountEvent
	8,  // 19: pbx.Plugin.Topic:input_type -> pbx.TopicEvent
	10, // 20: pbx.Plugin.Subscription:input_type -> pbx.SubscriptionEvent
	11, // 21: pbx.Plugin.Message:input_type -> pbx.MessageEvent
	3,  // 22: pbx.Plugin.FireHose:output_type -> pbx.ServerResp
	7,  // 23: pbx.Plugin.Find:output_type -> pbx.SearchFound
	2,  // 24: pbx.Plugin.Account:output_type -> pbx.Unused
	2,  // 25: pbx.Plugin.Topic:output_type -> pbx.Unused
	2,  // 26: pbx.Plugin.Subscription:output_type -> pbx.Unused
	2,  // 27: pbx.Plugin.Message:output_type -> pbx.Unused
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_chat_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
